# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

# Global filter for GitHub actions directory -- changes will be rejected by commit
FILTER_REGEX_EXCLUDE: ".*github/workflows/.*"

DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_KICS
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRUFFLEHOG
  - CSHARP_DOTNET_FORMAT # Expects a solution and csproj root, csharpier is better

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

# Powershell configuration
# My PSScriptAnalyzerSettings.psd1 contains the rules for formatting and linting
POWERSHELL_POWERSHELL_FORMATTER_CONFIG_FILE: ./Atelier/pwsh/PSScriptAnalyzerSettings.psd1
POWERSHELL_POWERSHELL_CONFIG_FILE: ./Atelier/pwsh/PSScriptAnalyzerSettings.psd1

# Configuration needed to ignore items from ./.config/awesome/awesome-wm-widgets/
# TODO: (Derek Lomax) 2/10/2025 1:32:23 PM, maybe remove awesome-wm-widgets from the repository (I've made no changes, it could be ignored)
# This is my raw git clone of the repository https://github.com/streetturtle/awesome-wm-widgets
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: ".*awesome-wm-widgets.*"
LUA_LUACHECK_FILTER_REGEX_EXCLUDE: ".*awesome-wm-widgets.*"
LUA_SELENE_FILTER_REGEX_EXCLUDE: ".*awesome-wm-widgets.*"

LUA_STYLUA_CONFIG_FILE: ".stylua.toml"

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
DISABLE_ERRORS: true
