# # Warning: This config does not include keys that have an unset value

# $all is shorthand for $username$hostname$localip$shlvl$singularity$kubernetes$directory$vcsh$fossil_branch$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$pijul_channel$docker_context$package$bun$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$golang$gradle$haskell$haxe$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$solidity$swift$terraform$vlang$vagrant$zig$buf$guix_shell$nix_shell$conda$meson$spack$memory_usage$aws$gcloud$openstack$azure$env_var$crystal$custom$sudo$cmd_duration$line_break$jobs$battery$time$status$container$os$shell$character
"$schema" = "https://starship.rs/config-schema.json"
# format = "$all"
right_format = ""
continuation_prompt = '[▶▶ ](purple)'
scan_timeout = 60
command_timeout = 1000
add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'
vimcmd_symbol = '[](bold yellow)'

[git_commit]
commit_hash_length = 7
only_detached = true
tag_symbol = ' 🔖'
tag_disabled = false

# git_status meanings

# Find all untracked branches
# git branch --format "%(refname:short) %(upstream)"
[git_status]
# For mega repos such as esp-adf this will kill performance if enabled
ignore_submodules = true
format = '([⎨$all_status$ahead_behind⎬]($style) )'
style = 'bold #9090FF'
conflicted = '[X](red)'
up_to_date = '[✓](#00FF00)'
untracked = '[](#666666)'
stashed = '[S](white)'
modified = '[M](#77CCFF)'
staged = '[++\($count\)](blue)'
renamed = '[R](cyan)'
deleted = '[D](#6E260E)'
ahead = '+${count}'
diverged = 'me+${ahead_count},rmt+${behind_count}'
behind = '-${count}'

[shell]
fish_indicator = '󰈺 '
powershell_indicator = ''
bash_indicator = ''
zsh_indicator = 'Z'
cmd_indicator = '󰇷'
nu_indicator = 'nu>'
unknown_indicator = ''
style = 'dimmed purple'
disabled = false

## I don't really like directory truncation
# [directory]
# truncation_length = 3
# truncation_symbol = "…/"

[directory.substitutions]
'\\\\' = '/'
'finance' = '💰'
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Way too slow! Use a environment variable instead some day
# [custom.ps_version]
# when = true
# command = '$PSVersionTable.PSVersion.ToString()'
# shell = ['pwsh.exe', '-NoProfile', '-Command', '-']

[os]
disabled = false
style = "bold #C75E16"
#FF00FF= "[$symbol]($style)" # Format for displaying OS symbol and name

# This is the default symbols table.
[os.symbols]
AIX = "➿ "
Alpaquita = "🔔 "
AlmaLinux = "💠 "
Alpine = "🏔️ "
Amazon = "🙂 "
Android = "🤖 "
Arch = "󰣇 "
Artix = "🎗️ "
CentOS = "💠 "
Debian = "🌀 "
DragonFly = "🐉 "
Emscripten = "🔗 "
EndeavourOS = "🚀 "
Fedora = "🎩 "
FreeBSD = "😈 "
Garuda = "🦅 "
Gentoo = "🗜️ "
HardenedBSD = "🛡️ "
Illumos = "🐦 "
Kali = "🐉 "
Linux = "🐧 "
Mabox = "📦 "
Macos = "🍎 "
Manjaro = "🥭 "
Mariner = "🌊 "
MidnightBSD = "🌘 "
Mint = "🌿 "
NetBSD = "🚩 "
NixOS = "❄️ "
OpenBSD = "🐡 "
OpenCloudOS = "☁️ "
openEuler = "🦉 "
openSUSE = "🦎 "
OracleLinux = "🦴 "
Pop = "🍭 "
Raspbian = "🍓 "
Redhat = "🎩 "
RedHatEnterprise = "🎩 "
RockyLinux = "💠 "
Redox = "🧪 "
Solus = "⛵ "
SUSE = "🦎 "
Ubuntu = " "
Ultramarine = "🔷 "
Unknown = "❓ "
Void = "  "
Windows = " "

# Slow things I don't want
[java]
disabled = true
