
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ShowOffTUI {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.TabView tabView;
        
        private Terminal.Gui.Button button1;
        
        private Terminal.Gui.Label label1;
        
        private void InitializeComponent() {
            this.label1 = new Terminal.Gui.Label();
            this.button1 = new Terminal.Gui.Button();
            this.tabView = new Terminal.Gui.TabView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "Press Ctrl+Q to quit";
            this.tabView.Width = Dim.Percent(50);
            this.tabView.Height = 14;
            this.tabView.X = 0;
            this.tabView.Y = 0;
            this.tabView.Visible = true;
            this.tabView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.tabView.CanFocus = true;
            this.tabView.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.tabView.Data = "tabView";
            this.tabView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.tabView.MaxTabTextWidth = 30u;
            this.tabView.Style.ShowBorder = true;
            this.tabView.Style.ShowTopLine = true;
            this.tabView.Style.TabsOnBottom = false;
            Terminal.Gui.Tab tabViewtab1;
            tabViewtab1 = new Terminal.Gui.Tab();
            tabViewtab1.DisplayText = "Tab1";
            tabViewtab1.View = new View();
            tabViewtab1.View.Width = Dim.Fill();
            tabViewtab1.View.Height = Dim.Fill();
            tabView.AddTab(tabViewtab1, false);
            Terminal.Gui.Tab tabViewtab2;
            tabViewtab2 = new Terminal.Gui.Tab();
            tabViewtab2.DisplayText = "Tab2";
            tabViewtab2.View = new View();
            tabViewtab2.View.Width = Dim.Fill();
            tabViewtab2.View.Height = Dim.Fill();
            tabView.AddTab(tabViewtab2, false);
            this.tabView.ApplyStyleChanges();
            this.Add(this.tabView);
            this.button1.Width = Dim.Auto();
            this.button1.Height = Dim.Auto();
            this.button1.X = Pos.Center();
            this.button1.Y = Pos.Center() + 1;
            this.button1.Visible = true;
            this.button1.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.button1.CanFocus = true;
            this.button1.ShadowStyle = Terminal.Gui.ShadowStyle.Opaque;
            this.button1.Data = "button1";
            this.button1.Text = "Click Me";
            this.button1.TextAlignment = Terminal.Gui.Alignment.Center;
            this.button1.IsDefault = false;
            this.Add(this.button1);
            this.label1.Width = Dim.Auto();
            this.label1.Height = 1;
            this.label1.X = Pos.Center();
            this.label1.Y = Pos.Center();
            this.label1.Visible = true;
            this.label1.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.label1.CanFocus = false;
            this.label1.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.label1.Data = "label1";
            this.label1.Text = "Hello World";
            this.label1.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label1);
        }
    }
}
