[user_interface]
text_editor = 'C:\windows\system32\notepad.exe'
default_protocol = "FTPS"
show_hidden_files = true
check_for_updates = true
prompt_on_file_replace = true
notifications = true
notification_threshold = 536870912

[remote.ssh_keys]
