name: Test my awesome window manager lua configuration

on: [push]

jobs:
  test:
    name: Pester Test Runner on ${{ matrix.container }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - archlinux:latest
    container:
      image: ${{ matrix.container }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install awesomewm
        run: |
          case ${{ matrix.container }} in
            archlinux*)
              pacman -Sy --noconfirm wget git base-devel sudo awesome
              ;;
          esac

      - name: Test awesomewm lua configuration
        run: |
          awesome --check ./.config/awesome/rc.lua

      - name: Try running awesome window manager to better test configuration
        run: |
          awesome --config ./.config/awesome/rc.lua
