---
name: Test MyCrossPlatformDotfiles Powershell Modules

on: [workflow_dispatch, push]

permissions: read-all

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install required powershell modules
        run: ./Atelier/pwsh/Bootstrap-RequiredModules.ps1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4

      - name: Run Pester Tests
        run: |
          $env:PSModulePath += "$([System.IO.Path]::PathSeparator)./Atelier/pwsh/MyModules/"
          $config = New-PesterConfiguration -Hashtable @{
              Run = @{
                  PassThru = $true
                  Path = './Atelier/pwsh/MyModules'
              }
              Debug = @{
                  WriteDebugMessages = $true
              }
              Output = @{Verbosity = 'Detailed' }
          }
          Get-PackageProvider
          Invoke-Pester -Configuration $config
          Get-PackageProvider
          Get-PackageProvider -ListAvailable
          Get-Package -ErrorAction SilentlyContinue | Group-Object -Property Provider
