name: Run Pester Tests Windows

# Only run workflow if dots powershell module has changed
on:
  workflow_dispatch:
  push:
    paths:
      - Atelier/pwsh/**

jobs:
  test:
    name: Pester Test Runner on ${{ matrix.windows_version }}
    runs-on: ${{ matrix.windows_version }}

    strategy:
      fail-fast: false
      matrix:
        windows_version:
          - windows-2022  # Equivalent to windows-latest
          - windows-2019

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Pester and Other Required Modules
        shell: pwsh
        run: |
          Install-Module -Name Pester -RequiredVersion 5.3.1 -Force -SkipPublisherCheck
          pwsh -File './Atelier/pwsh/Bootstrap-RequiredModules.ps1'

      - name: Run Pester Tests
        shell: pwsh
        run: |
          $env:PSModulePath += ';./Atelier/pwsh/MyModules'
          Invoke-Pester -Path './Atelier/pwsh' -Passthru -Output Detailed
