name: Run Pester Tests on Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Pester Test Runner on ${{ matrix.container }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - debian:bullseye
          - fedora:latest
          - archlinux:latest
    container:
      image: ${{ matrix.container }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install and Setup PowerShell and Pester
        run: |
          case ${{ matrix.container }} in
            debian*)
              apt-get update && apt-get install -y wget apt-transport-https git software-properties-common
              wget -q "https://packages.microsoft.com/config/debian/$(. /etc/os-release && echo $VERSION_ID)/packages-microsoft-prod.deb"
              dpkg -i packages-microsoft-prod.deb
              apt-get update && apt-get install -y powershell git
              pwsh -Command "Install-Module -Name Pester -Force -SkipPublisherCheck"
              ;;
            fedora*)
              rpm --import https://packages.microsoft.com/keys/microsoft.asc
              rpm -Uvh https://packages.microsoft.com/config/centos/8/packages-microsoft-prod.rpm
              dnf makecache
              dnf install -y powershell git
              pwsh -Command "Install-Module -Name Pester -Force -SkipPublisherCheck"
              ;;
            archlinux*)
              pacman -Sy --noconfirm wget git base-devel sudo
              useradd -m builduser
              passwd -d builduser
              echo "builduser ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers
              sudo -u builduser bash -c "cd; git clone https://aur.archlinux.org/powershell-bin.git; cd powershell-bin; makepkg -si --noconfirm"
              sudo -u builduser pwsh -Command "Install-Module -Name Pester -Force -SkipPublisherCheck"
              export PATH=$PATH:/home/builduser/.local/share/powershell/Modules
              sudo -E pwsh -Command "Get-Module -ListAvailable Pester"
              sudo -E pwsh -Command "Invoke-Pester -Path './Scripts/Tests' -Passthru -Output Detailed"
              ;;
          esac

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path './Scripts/Tests' -Passthru -Output Detailed
