name: Run Pester Tests on Linux

on: [push, pull_request]

jobs:
  test:
    name: Pester Test Runner on ${{ matrix.container }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container:
          - ubuntu:22.04
          - debian:bullseye
          - centos:8
          - alpine:latest

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          if [ -f /etc/debian_version ]; then
            # Debian and Ubuntu
            apt-get update
            apt-get install -y wget apt-transport-https git software-properties-common
            wget -q "https://packages.microsoft.com/config/debian/$(. /etc/os-release && echo $VERSION_ID)/packages-microsoft-prod.deb"
            dpkg -i packages-microsoft-prod.deb
            apt-get update
            apt-get install -y powershell
          elif [ -f /etc/centos-release ]; then
            # CentOS
            yum clean all
            yum makecache
            yum install -y wget git powershell
          elif [ -f /etc/alpine-release ]; then
            # Alpine
            apk add --no-cache git
            apk add --no-cache powershell
            # Configuring PowerShell for limited Alpine functionality
            pwsh -Command "
              [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
              Find-Module Pester | Install-Module -Force
            "
          fi

      - name: Install and Configure PowerShell Environment
        run: |
          if [ ! -f /etc/alpine-release ]; then
            pwsh -Command "
              [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
              Install-Module -Name PowerShellGet -Force -AllowClobber
              Install-Module -Name Pester -RequiredVersion 5.3.1 -Force -SkipPublisherCheck
            "
          fi

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path './Scripts/Tests' -Passthru -Output Detailed
