name: Run Pester Tests on Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Pester Test Runner on ${{ matrix.container }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - debian:bullseye
          - fedora:latest
          - archlinux:latest
    container:
      image: ${{ matrix.container }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install and Setup PowerShell and Pester
        run: |
          case ${{ matrix.container }} in
            debian*)
              apt-get update && apt-get install -y wget apt-transport-https git software-properties-common
              wget -q "https://packages.microsoft.com/config/debian/$(. /etc/os-release && echo $VERSION_ID)/packages-microsoft-prod.deb"
              dpkg -i packages-microsoft-prod.deb
              apt-get update && apt-get install -y powershell
              pwsh -Command "Install-Module -Name Pester -Force -SkipPublisherCheck"
              ;;
            fedora*)
              rpm --import https://packages.microsoft.com/keys/microsoft.asc
              curl https://packages.microsoft.com/config/fedora/$(. /etc/os-release && echo $VERSION_ID)/prod.repo | tee /etc/yum.repos.d/microsoft.repo
              dnf makecache
              dnf install -y powershell
              pwsh -Command "Install-Module -Name Pester -Force -SkipPublisherCheck"
              ;;
            archlinux*)
              pacman -Sy --noconfirm wget git base-devel sudo
              useradd -m builduser
              passwd -d builduser
              echo "builduser ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers
              sudo -u builduser sh -c "cd; curl -L https://github.com/PowerShell/PowerShell/releases/download/v7.2.0/powershell-7.2.0-linux-x64.tar.gz | tar xz"
              sudo -u builduser sh -c "cd; ./powershell/./pwsh -Command 'Install-Module -Name Pester -Force -SkipPublisherCheck'"
              ;;
          esac

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path './Scripts/Tests' -Passthru -Output Detailed
