---
name: Test MyCrossPlatformDotfiles Powershell Modules

on: [workflow_dispatch, push]

permissions: read-all

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install required powershell modules
      run: ./Atelier/pwsh/Bootstrap-RequiredModules.ps1

    - name: Run Pester Tests
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: '9.x'
    - run: |
        $env:PSModulePath += "$([System.IO.Path]::PathSeparator)./Atelier/pwsh/MyModules/"
        Import-Module Pester -Force
        Invoke-Pester -Path './Atelier/pwsh/MyModules' -Passthru -Output Detailed
