jobs:
  test:
    name: Pester Test Runner on ${{ matrix.container }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - ubuntu:22.04
          - debian:bullseye
          - centos:8
          - alpine:latest
    container:
      image: ${{ matrix.container }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Environment for Debian
        if: contains(matrix.container, 'debian')
        run: |
          echo "DOTNET_CLI_TELEMETRY_OPTOUT=true" >> $GITHUB_ENV

      - name: Install and Setup Environment
        run: |
          if [ -f /etc/debian_version ]; then
            apt-get update && apt-get install -y wget apt-transport-https git software-properties-common
            wget -q "https://packages.microsoft.com/config/debian/$(. /etc/os-release && echo $VERSION_ID)/packages-microsoft-prod.deb"
            dpkg -i packages-microsoft-prod.deb
            apt-get update && apt-get install -y powershell
          elif [ -f /etc/centos-release ]; then
            yum clean all
            yum makecache --disablerepo='*' --enablerepo='base,updates'
            yum install -y powershell
          elif [ -f /etc/alpine-release ]; then
            apk add --no-cache git
            apk add --no-cache powershell
            # Configure necessary tools if available
            # Alternative setup or module installation methods may be required
          fi

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path './Scripts/Tests' -Passthru -Output Detailed
